### ISSUE TITLE
Appendix E (MCMC and Gibbs-Sampler)

### ISSUE THREAD

**Issue by JSainath** [trevorlolsen/outline#1]
Trevor, 

This section has a lot of duplication of information. 

The goal should be to synthesize information from the different sources into one write up while providing references where needed. Please adopt a single notational convention (that matches what you are using for the choice model). 

The following Sections (-) and Subsections (*) should be enough: 
- General Intro to MCMC
* Gibbs
* MH
- General Implementation Issues
- Specific Convergence Issues

**Comment by trevorlolsen** [comment]
Yes, there is a lot of duplication and inconsistent notations (Not just in the MCMC section). These are just my notes at the moment. I'm working on consolidation.

**Comment by JSainath** [comment]
Sounds good.
