### ISSUE TITLE
Appendix F

### ISSUE THREAD

**Issue by JSainath** [trevorlolsen/outline#12]
<img width="329" alt="Screen Shot 2020-06-16 at 3 20 32 PM" src="https://user-images.githubusercontent.com/65315822/84829998-f0c47580-afe5-11ea-88b1-97b552b26e8c.png">
<img width="446" alt="Screen Shot 2020-06-16 at 3 31 26 PM" src="https://user-images.githubusercontent.com/65315822/84830002-f28e3900-afe5-11ea-81e6-d2cecc79c472.png">

<img width="781" alt="Screen Shot 2020-06-16 at 3 35 45 PM" src="https://user-images.githubusercontent.com/65315822/84830405-90820380-afe6-11ea-9777-7f537b47a09b.png">

**Comment by trevorlolsen** [comment]
Updated, but wording on f.2.1 may still not be what you'd like:

![image](https://user-images.githubusercontent.com/47762165/84832173-05a30800-afea-11ea-8da3-70c74f8f9f04.png)

**Comment by JSainath** [comment]
> Updated, but wording on f.2.1 may still not be what you'd like:
> 
> ![image](https://user-images.githubusercontent.com/47762165/84832173-05a30800-afea-11ea-8da3-70c74f8f9f04.png)

For "Keep" and "R", use: This was set to .. 
Otherwise, ok.

**Comment by trevorlolsen** [comment]
Great. Made that change:
![image](https://user-images.githubusercontent.com/47762165/84836424-f3799780-aff2-11ea-906d-826724d5115d.png)

**Comment by JSainath** [comment]
> Great. Made that change:
> ![image](https://user-images.githubusercontent.com/47762165/84836424-f3799780-aff2-11ea-906d-826724d5115d.png)

Ok!
