### ISSUE TITLE
Equation 54

### ISSUE THREAD

**Issue by JSainath** [trevorlolsen/outline#2]
Pls simplify notation: something like $\forall i \neq j$ should be enough.

**Comment by trevorlolsen** [comment]
The problem is that there are three indices for the spefici use case.
n - decision maker
s - specific choice set
i - the specific alternative of the choice set s.

**Comment by JSainath** [comment]
You can define the notation once to mean what it does above equation (52) and just use the simpler form. It would make reading far easier subsequently.

**Comment by trevorlolsen** [comment]
Okay, I'll do something like that. Thanks.
