### ISSUE TITLE
Section E2(Markov Chains)

### ISSUE THREAD

**Issue by JSainath** [trevorlolsen/outline#3]
[Here](https://www.dartmouth.edu/~chance/teaching_aids/books_articles/probability_book/Chapter11.pdf) is a document that gives a fairly general introduction to MCs & stationary distributions - if you are looking for a reference.

**Comment by trevorlolsen** [comment]
Thanks for the extra reference. It looks like it only covers discrete space chains (which is the problem with most introductory references), but I'll try and use what I can. Thanks.

**Comment by JSainath** [comment]
The definitions don't change much as long as we replace discrete time points with $t$ and $t + \Delta t$.

**Comment by JSainath** [comment]
Some definitions that need to be included are: 

- Reversibile MC and Symmetry
- Ergodicity

**Comment by JSainath** [comment]
Check these [notes](http://home.uchicago.edu/~guptav/teaching/notes_queueing.pdf) from page 27 onwards for continuous time MC.

**Comment by JSainath** [comment]
Hi Trevor, 

Please see [this](http://www.cs.columbia.edu/~blei/fogm/2014F/readings/Neal1993.pdf) reference (Pages 37-38) for an explanation for Ergodicity. You can ignore the proof.

**Comment by trevorlolsen** [comment]
Do you want me to not use the definition given by RAM on page 51? Thanks

**Comment by trevorlolsen** [comment]
The bottom of page 42 of Neal paper states that the fundamental theorem doesn't hold as stated on page 38 for continuous state spaces.

**Comment by JSainath** [comment]
What you could do is the following: 
1.  Retain the definition. 
2. State that this implies that immaterial of the starting point in the state space, the chain will converge to its stationary distribution. 
3. Ergodicity implies that the strong law of large numbers holds. 

You can ignore the theorem, you are right.

**Comment by trevorlolsen** [comment]
Will do, thanks.

**Comment by JSainath** [comment]
Section: E.2.3 Dependence

"Fortunately, there are versions of the law of large numbers for dependent but stationary sequences. " 

It would be good to include references for that sentence.

**Comment by JSainath** [comment]
If I remember right, you are using 1 out of 10 draws to deal with the correlation?

**Comment by trevorlolsen** [comment]
Ram gives the result that the distributions convergence:

![image](https://user-images.githubusercontent.com/47762165/83566265-f9dd1f00-a4dc-11ea-8fe4-945490b4d838.png)

Radford's fundamental theorem appears to be more general:

![image](https://user-images.githubusercontent.com/47762165/83566383-298c2700-a4dd-11ea-8f0c-c91e5a27b67c.png)


I don't remember Math 6070 as well as I should, but I know there are different kinds of convergences:

**Comment by trevorlolsen** [comment]
We discussed keeping every draw, but my computer worked a lot better if I kept every 2nd draw. RAM says there is no reason not to keep every draw.


![image](https://user-images.githubusercontent.com/47762165/83567673-2db94400-a4df-11ea-8186-70ec116d0ddc.png)

**Comment by trevorlolsen** [comment]
I'm currently working on the MCMC section. Added the references like you called out.

**Comment by JSainath** [comment]
ok, on the correlation issue.

**Comment by JSainath** [comment]
If I remember my earlier reading correctly, ergodicity implies almost sure convergence. But, let me reconfirm this.

**Comment by trevorlolsen** [comment]
Is it sufficient to reference chapter 9 from the  Math 6070 (Asymptotic theory of statistics and probability)?


![image](https://user-images.githubusercontent.com/47762165/83569122-41fe4080-a4e1-11ea-9db1-3631f4d74130.png)


I have no idea is this is the theory that RAM is referring to about the dependency not being an issue for the CLT. I'm having a hard time knowing what is required for stating the MCMC theory.

**Comment by JSainath** [comment]
Let me check on this and get back to you.

**Comment by trevorlolsen** [comment]
Thanks

**Comment by JSainath** [comment]
> What you could do is the following:
> 
> 1. Retain the definition.
> 2. State that this implies that immaterial of the starting point in the state space, the chain will converge to its stationary distribution.
> 3. Ergodicity implies that the strong law of large numbers holds.
> 
> You can ignore the theorem, you are right.

The convergence is "almost surely" - the stronger form of convergence. It is the same as point-wise convergence. You could state the definition and add "a.s." at the end of the equation box. 

For now, you could reference this textbook: 
 ftp://nozdr.ru/biblio/kolxoz/G/GL/Handbook%20of%20econometrics,%20Vol.5%20(Elsevier,%202001)(ISBN%200444823409)(O)(741s)_GL_.pdf#page=436

(Page 3579). 

We should find a better reference (where there is also a proof to support the statement). Will get back to you on that.

**Comment by JSainath** [comment]
> Is it sufficient to reference chapter 9 from the Math 6070 book (Asymptotic theory of statistics and probability)?
> 
> ![image](https://user-images.githubusercontent.com/47762165/83569122-41fe4080-a4e1-11ea-9db1-3631f4d74130.png)
> 
> I have no idea if this is the theory that RAM is referring to about the dependency not being an issue for the CLT. I'm having a hard time knowing what is required for stating the MCMC theory.

Yes, this should be enough for now.

**Comment by trevorlolsen** [comment]
Thanks!

**Comment by JSainath** [comment]
> Is it sufficient to reference chapter 9 from the Math 6070 book (Asymptotic theory of statistics and probability)?
> 
> ![image](https://user-images.githubusercontent.com/47762165/83569122-41fe4080-a4e1-11ea-9db1-3631f4d74130.png)
> 
> I have no idea if this is the theory that RAM is referring to about the dependency not being an issue for the CLT. I'm having a hard time knowing what is required for stating the MCMC theory.

The particular CLT version that you need to reference:

https://link.springer.com/article/10.1007/BF01210789

**Comment by trevorlolsen** [comment]
Great! Thanks for finding it.

**Comment by trevorlolsen** [comment]
Should I just reference the paper or a particular theorem? If I should reference a particular theorem,  is it theorem 1.3? I think that is stating what we need.

**Comment by JSainath** [comment]
> Should I just reference the paper or a particular theorem? If I should reference a particular theorem, is it theorem 1.3? I think that is stating what we need.

Just the paper should be enough.

**Comment by trevorlolsen** [comment]
Will do, Thanks!

**Comment by trevorlolsen** [comment]
I don't know if this will work, but I added section E.2.1.6 that covers all the definitions from Tierney and section E.2.1.7 that states all the convergence theorems.

**Comment by JSainath** [comment]
Ok!
