### ISSUE TITLE
Abstract 

### ISSUE THREAD

**Issue by JSainath** [trevorlolsen/outline#9]
<img width="317" alt="Screen Shot 2020-06-15 at 3 10 20 PM" src="https://user-images.githubusercontent.com/65315822/84706244-e2108c80-af19-11ea-801d-3bf4d0577a33.png">
<img width="481" alt="Screen Shot 2020-06-15 at 3 10 10 PM" src="https://user-images.githubusercontent.com/65315822/84706250-e50b7d00-af19-11ea-9383-c6a8c17259fc.png">

**Comment by trevorlolsen** [comment]
Thanks for the feedback! I made and pushed those changes.
